n1 = float(input("\nIngresa el primer número: "))
n2 = float(input("Ingresa el segundo número: "))
print("n1 == n2:", n1 == n2)
print("n1 != n2:", n1 != n2)
print("n1 > n2:", n1 > n2)
print("n1 < n2:", n1 < n2)
print("n1 >= n2:", n1 >= n2)
print("n1 <= n2:", n1 <= n2)